### ISSUE TITLE
why return error as data?

### ISSUE THREAD

**Issue by ahdinosaur** [sheetify/sheetify-cssnext#1]
hey @hughsk, question about [index.js#L17](https://github.com/sheetify/sheetify-cssnext/blob/master/index.js#L17) from @eedrah:

> Question - node-style callbacks have the first parameter as an error, right? and then data for the others?
> 
> I'm trying to make sense of line 17 and line 20 - why isn't line 17 putting the error in the first parameter?
> 
> https://github.com/sheetify/sheetify-cssnext/blob/master/index.js

**Comment by hughsk** [comment]
Oops! Line 17 should be `done(e)` and not `done(null, e)` :)

**Comment by eedrah** [comment]
#2 fixes :)
